"use client";
import Link from "next/link";
import { CheckCircle2, MinusCircle } from "lucide-react";
import { toast } from "sonner";
import { useApp } from "@/components/app/app-context";
import { Badge } from "@/components/ui/misc";
import { errorMessage } from "@/lib/client/api";
import { mayUseAi } from "@/lib/ai/privacy";
import type { Preferences } from "@/lib/types";
import { Row, Section, Segmented, ToggleRow } from "./parts";

function Status({ on, label, detail }: { on: boolean; label: string; detail: string }) {
  return (
    <li className="flex items-start gap-3 text-sm">
      {on ? <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-ok" aria-hidden /> : <MinusCircle className="mt-0.5 h-4 w-4 shrink-0 text-muted" aria-hidden />}
      <div><p className="font-medium">{label} <Badge tone={on ? "ok" : "neutral"}>{on ? "Configured" : "Not configured"}</Badge></p><p className="text-xs text-muted">{detail}</p></div>
    </li>
  );
}

export function AiTab() {
  const { caps, prefs, updatePrefs } = useApp();
  const save = (patch: Partial<Preferences>) => void updatePrefs(patch).catch((e) => toast.error(errorMessage(e)));
  const aiAllowed = mayUseAi(prefs.processing_mode, caps.aiLocality);
  return (
    <div className="space-y-5">
      <Section title="AI on this server" description="Set by whoever runs this server through environment variables. Keys and endpoints are never shown here.">
        <ul className="space-y-3">
          <Status on={caps.ai} label="Answers and summaries" detail={caps.ai ? `Provider is ${caps.aiLocality === "local" ? "self-hosted" : "a cloud service"}.` : "Without a provider, Ask AI lists matching passages and files instead of writing answers."} />
          <Status on={caps.embeddings} label="Semantic search" detail={caps.embeddings ? `Embeddings are generated by ${caps.embeddingsLocality === "local" ? "a self-hosted" : "a cloud"} model.` : "Search uses keywords, names and dates only."} />
          <Status on={caps.ocr} label="Text from images (OCR)" detail={caps.ocr ? "Images and scanned pages are read for text." : "Text inside images isn't extracted."} />
          <Status on={caps.transcription} label="Audio and video transcription" detail={caps.transcription ? "Spoken audio is transcribed so it can be searched." : "Audio and video are indexed by name and metadata only."} />
        </ul>
        <p className={aiAllowed ? "text-sm text-muted" : "rounded-lg border border-warn/40 bg-warn/10 p-3 text-sm"}>
          {aiAllowed ? "Your privacy mode allows content to be sent to the AI provider above." : <>With your current privacy mode, no content is sent to an AI provider, even if one is configured. <Link href="/settings?tab=privacy" className="underline">Review privacy mode</Link></>}
        </p>
      </Section>
      <Section title="Answers">
        <Row label="Answer style" description="How long and detailed written answers should be."><Segmented label="Answer style" value={prefs.response_style} onChange={(v) => save({ response_style: v })} options={[{ value: "concise", label: "Concise" }, { value: "balanced", label: "Balanced" }, { value: "detailed", label: "Detailed" }]} /></Row>
        <ToggleRow id="recency" label="Prefer recent items" description="Newer matches rank slightly higher when relevance is similar." checked={prefs.search_recency_boost} onChange={(v) => save({ search_recency_boost: v })} />
        <p className="text-xs text-muted">Answers are written only from items found in your memory and cite them. They can still be wrong; check the sources.</p>
      </Section>
    </div>
  );
}
